# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

"""

import pandas as pd
import re

df = pd.read_csv(
    "sms-classification-dataset.csv",
    encoding="windows-1252",
    sep=";",
    engine="python"
)

def fix_turkish(text):
    if isinstance(text, str):
        try:
            return text.encode("windows-1252").decode("iso-8859-9")
        except:
            return text
    return text

df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
df["text"] = df["text"].apply(fix_turkish)
df["groupText"] = df["groupText"].apply(fix_turkish)

print("Orijinal veri boyutu:", df.shape)

def create_masked_text(text):
    if not isinstance(text, str):
        return text

    # URL
    text = re.sub(r'https?://\S+|www\.\S+', '<URL>', text)

    # Telefon
    text = re.sub(
        r'\b(\+90\s?|0)(5\d{2}|2\d{2}|3\d{2})\s?\d{3}\s?\d{2}\s?\d{2}\b',
        '<PHONE>',
        text
    )

    # Yüzde
    text = re.sub(
        r'%\s*\d+([.,]\d+)?',
        '<PERCENT>',
        text
    )

    # Fiyat
    text = re.sub(
        r'\b\d{1,3}([.,]\d{3})*([.,]\d+)?\s*(TL|₺)\b',
        '<PRICE>',
        text,
        flags=re.IGNORECASE
    )

    return text

df["masked_text"] = df["text"].apply(create_masked_text)

df_clean = df.drop_duplicates(subset=["masked_text"])

df_clean = df.drop_duplicates(subset=["masked_text"])

df.to_csv(
    "sms_dataset_balanced.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)