# -*- coding: utf-8 -*-
"""word_cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOvF3ORlCyA8XqfQZ4h_sW51HGnnpUha
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %run "/content/drive/MyDrive/Colab Notebooks/SmsClassification.ipynb"

!pip install wordcloud matplotlib

import numpy as np

def circle_mask(size=800):
    y, x = np.ogrid[:size, :size]
    center = size // 2
    radius = size // 2 - 20


    mask = (x - center)**2 + (y - center)**2 <= radius**2
    return mask

turkish_stopwords = set([
    "ve", "bir", "bu", "da", "de", "mi", "mu", "mı", "mü",
    "ile", "için", "ama", "fakat", "çok", "daha", "en",
    "gibi", "olan", "olarak", "şu", "o", "ben", "sen",
    "biz", "siz", "onlar"
])

presentation_stopwords = turkish_stopwords.union({
    "url", "phone", "price","percent","tel"
})

import matplotlib.pyplot as plt
from wordcloud import WordCloud

def plot_inside_wordcloud(texts, title):
    text = " ".join(texts)
    mask = circle_mask(800)

    wc = WordCloud(
        width=800,
        height=800,
        background_color="white",
        mask=mask,

        stopwords=presentation_stopwords,
        max_words=200,
        max_font_size=90,
        min_font_size=12,
        relative_scaling=0.1,
        prefer_horizontal=0.9,
        repeat=True,

        collocations=False,
        contour_width=0,
        colormap="viridis"
    ).generate(text)

    plt.figure(figsize=(8, 8))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(title, fontsize=16)
    plt.tight_layout(pad=0)
    plt.show()

fraud_texts = df[df["group"] == 0]["masked_text"].dropna().astype(str)
plot_inside_wordcloud(fraud_texts, "Dolandırıcılık SMS'leri – Word Cloud")